runtime: python39

env_variables:
  DOMAIN: kinggrouptech.com
  API_URL: https://kinggrouptech-93908.appspot.com
  WEB_URL: https://kinggrouptech.com
  APP_URL: https://app.kinggrouptech.com

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

network:
  forwarded_ports:
  - 8080

